# Generated by Django 3.1.6 on 2021-02-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_product', models.IntegerField()),
                ('fk_seller', models.IntegerField()),
                ('fk_category', models.IntegerField()),
                ('approved', models.BooleanField()),
            ],
        ),
    ]
