# Generated by Django 3.1.6 on 2021-02-10 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_product', models.IntegerField()),
                ('fk_seller', models.IntegerField()),
                ('fk_category', models.IntegerField()),
                ('approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('height', models.DecimalField(decimal_places=2, max_digits=9)),
                ('width', models.DecimalField(decimal_places=2, max_digits=9)),
                ('length', models.DecimalField(decimal_places=2, max_digits=9)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pool',
        ),
        migrations.AddField(
            model_name='cataloganalysis',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.category'),
        ),
        migrations.AddField(
            model_name='cataloganalysis',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.product'),
        ),
        migrations.AddField(
            model_name='cataloganalysis',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.seller'),
        ),
    ]
