# Generated by Django 3.1.6 on 2021-02-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0002_auto_20210210_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cataloganalysis',
            name='fk_category',
        ),
        migrations.RemoveField(
            model_name='cataloganalysis',
            name='fk_product',
        ),
        migrations.RemoveField(
            model_name='cataloganalysis',
            name='fk_seller',
        ),
    ]
